### ISSUE TITLE
Setup logging

### ISSUE THREAD

**Issue by TheJimmyNowak** [miki164/bookshelf#14]
We need to have logging in our app. I think the best choose is to logging everything to file using logging lib from python core.

Some useful links
- [Logging docs](https://docs.python.org/3/library/logging.html)
- [Logging with flask](https://www.scalyr.com/blog/getting-started-quickly-with-flask-logging/). I don't know if that link will be useful, although it's one of the ways to do that.

Good luck @Dlugi03 :wink:

**Comment by ghost** [comment]
Logging setted up
